### ISSUE TITLE
请问这是发生甚么事了

### ISSUE THREAD

**Issue by 2054686334** [Hellobaka/OPQBot-Native#2]
![image](https://user-images.githubusercontent.com/63030840/103144938-aed27400-476c-11eb-9752-1d87b8afa67d.png)
哭唧唧，运行不了

**Comment by Hellobaka** [comment]
请详细说明错误复现的步骤。
猜测是连接服务端的URL不正确，尝试使用以下格式`http://127.0.0.1:8888/`

**Comment by Hellobaka** [comment]
回复详情后，该issue将会再次开放
